// src/mockData.ts
export type Person = {
  id: number;
  name: string;
  nationalId: string;
  gender: "ذكر" | "أنثى";
  age: number;
  company: string;
  governorate: string;
};

 export const people: Person[] = [
  {
    id: 1,
    name: "خالد وليد محمد الحنيطي",
    nationalId: "1990120156781",
    gender: "ذكر",
    age: 35,
    company: "شركة المزارع الخضراء",
    governorate: "عمّان",
  },
  {
    id: 2,
    name: "نور أحمد محمود العزام",
    nationalId: "2997031523412",
    gender: "أنثى",
    age: 27,
    company: "المؤسسة الأردنية للمدخلات الزراعية",
    governorate: "إربد",
  },
  {
    id: 3,
    name: "محمد عيسى يوسف الخطيب",
    nationalId: "1989121022901",
    gender: "ذكر",
    age: 34,
    company: "شركة الري الحديث",
    governorate: "الزرقاء",
  },
  {
    id: 4,
    name: "سارة خليل عمر الطراونة",
    nationalId: "2998051014563",
    gender: "أنثى",
    age: 26,
    company: "مزارع وادي الأردن",
    governorate: "عمّان",
  },
  {
    id: 5,
    name: "أحمد رائد فايز الرواشدة",
    nationalId: "1991122508765",
    gender: "ذكر",
    age: 33,
    company: "شركة الأسمدة الطبيعية الأردنية",
    governorate: "الكرك",
  },
  {
    id: 6,
    name: "هديل محمود محمد العياصرة",
    nationalId: "2996091809321",
    gender: "أنثى",
    age: 29,
    company: "التعاونيات الزراعية المتحدة",
    governorate: "جرش",
  },
  {
    id: 7,
    name: "زيد ناصر خالد العبداللات",
    nationalId: "1993030511234",
    gender: "ذكر",
    age: 32,
    company: "شركة التكنولوجيا الزراعية الذكية",
    governorate: "عمّان",
  },
  {
    id: 8,
    name: "براءة يوسف حسن المومني",
    nationalId: "2000012028745",
    gender: "أنثى",
    age: 24,
    company: "مزارع البحر الأحمر",
    governorate: "العقبة",
  },
  {
    id: 9,
    name: "ليث سليم محمد بني ياسين",
    nationalId: "1995111127654",
    gender: "ذكر",
    age: 29,
    company: "شركة الاستدامة الزراعية",
    governorate: "مأدبا",
  },
  {
    id: 10,
    name: "رندة عادل حسين الشرمان",
    nationalId: "2998113034521",
    gender: "أنثى",
    age: 25,
    company: "تمكين المرأة الريفية",
    governorate: "الطفيلة",
  },
  {
    id: 11,
    name: "طارق حاتم سالم الدرابسة",
    nationalId: "1989121708876",
    gender: "ذكر",
    age: 35,
    company: "مزارع الجنوب للإنتاج النباتي",
    governorate: "معان",
  },
  {
    id: 12,
    name: "آية خالد جميل الخوالدة",
    nationalId: "2997070426678",
    gender: "أنثى",
    age: 27,
    company: "شركة إنتاج البذور الأردنية",
    governorate: "السلط",
  },
  {
    id: 13,
    name: "محمود سامر أحمد العتوم",
    nationalId: "1993100915467",
    gender: "ذكر",
    age: 31,
    company: "شركة الابتكار الزراعي",
    governorate: "إربد",
  },
  {
    id: 14,
    name: "دانا أيمن راشد القيسي",
    nationalId: "2999122222987",
    gender: "أنثى",
    age: 24,
    company: "حاضنة الأعمال الزراعية",
    governorate: "عمّان",
  },
  {
    id: 15,
    name: "باسل هيثم عبدالكريم الزعبي",
    nationalId: "1996011521986",
    gender: "ذكر",
    age: 28,
    company: "شركة محاصيل الوادي",
    governorate: "الزرقاء",
  },
  {
    id: 16,
    name: "هبة عبدالله محمد الجبور",
    nationalId: "2995040626541",
    gender: "أنثى",
    age: 30,
    company: "مركز دراسات المناخ الزراعي",
    governorate: "إربد",
  },
  {
    id: 17,
    name: "سامر عوض عبدالرحمن الشوبكي",
    nationalId: "1992073014321",
    gender: "ذكر",
    age: 33,
    company: "شركة الحصاد الذهبي",
    governorate: "جرش",
  },
  {
    id: 18,
    name: "ياسمين وائل جميل العواجزة",
    nationalId: "2998110912245",
    gender: "أنثى",
    age: 25,
    company: "شركة النباتات الطبية والعطرية",
    governorate: "عجلون",
  },
  {
    id: 19,
    name: "كرم نائل عمر الدعجة",
    nationalId: "1993103017975",
    gender: "ذكر",
    age: 31,
    company: "مزارع وادي الموجب",
    governorate: "الكرك",
  },
  {
    id: 20,
    name: "ميس عبدالرحمن خالد الخطيب",
    nationalId: "2996041818872",
    gender: "أنثى",
    age: 28,
    company: "الري بالتنقيط المتقدم",
    governorate: "عمّان",
  },
];

